app:
  Name: gdemo
  Version: 0.0.1
  GrpcAddr: :9000
  HttpAddr: :8080

config:
  test: json

consul:
  address: ${consul_addr}

jaeger:
  serviceName: ginny-demo
  reporter:
    logSpans: true
    localAgentHostPort: ${jaeger_agent}
  sampler:
    type: const
    param: 1
broker:
  dsn: ${broker_dsn}
  topic: kafkatest
mysql:
  db_name: test
  wdb:
    host: ${mysql_host}
    user: ${mysql_user}
    pass: ${mysql_pass}
  # rdbs:
  #   - host: ${mysql_host}
  #     user: ${mysql_user}
  #     pass: ${mysql_pass}
redis:
  db: 0
  pool_size:
  username:
  password: ${redis_pass}
  standalone:
    standalone_addrs:
      - master: ${redis_host}
        slaves:
          - ${redis_host}
  # sentinel:
  #   master_name:
  #   sentinel_addrs:
  #     - ${redis_host}
  #   sentinel_password:
  # cluster:
  #   cluster_addrs:
  #     - ${redis_host}
  #   max_redirects:
# mongo:
#   default_dbname:
#   hosts:
#     - ${mongo_host}
#   auth:
#     username:
#     password:
#   max_pool_size:
#   min_pool_size:
