app:
  name: gdemo
  Version: 0.0.1
  GrpcAddr: :9000
  HttpAddr: :8080

test: json

consul:
  address: ${consul_addr}

jaeger:
  serviceName: test
  reporter:
    localAgentHostPort: ${jaeger-agent}
  sampler:
    type: const
    param: 1

mysql:
  db_name: test
  wdb:
    host: ${mysql_host}
    user: ${mysql_user}
    pass: ${mysql_pass}
  # rdbs:
  #   - host: ${mysql_host}
  #     user: ${mysql_user}
  #     pass: ${mysql_pass}
redis:
  username:
  password: ${redis_pass}
  db: 0
  pool_size:
  standalone:
    standalone_addrs:
      - master: ${redis_host}
        slaves:
          - ${redis_host}
  # sentinel:
  #   master_name:
  #   sentinel_addrs:
  #     - ${redis_host}
  #   sentinel_password:
  # cluster:
  #   cluster_addrs:
  #     - ${redis_host}
  #   max_redirects:
# mongo:
#   default_dbname:
#   hosts:
#     - ${mongo_host}
#   auth:
#     username:
#     password:
#   max_pool_size:
#   min_pool_size:
