app:
  name: ginny-template
http:
  mode: release
  host: 127.0.0.1
  port: 9090
grpc:
  port: 0
consul:
  addr: ${consul_addr}
jaeger:
  serviceName: test
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
log:
  filename: ./logs/test.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
